### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by PapsOu** [sil-project/Platform#9]
In current .editorconfig's files (https://gist.github.com/PapsOu/04a02e8f5c4d9725c0f5082e6f842941) values should be changed as that one https://gist.github.com/PapsOu/d59dc8222c1c964fc0e565dfb80fb513

Someone have any reason to use 2 spaces instead of 4 ?
Any other remarks ?

**Comment by FanchTheSystem** [comment]
please remove composer and json part
and use tab for makefile as it is part of makefile syntax

**Comment by PapsOu** [comment]
This file has been accepted https://github.com/sil-project/Platform/commit/0cd735d1e20a38f823b97f9281ca8236f12622d4
